import { appSchema, tableSchema } from '@nozbe/watermelondb';

export default appSchema({
  version: 7,
  tables: [
    tableSchema({
      name: 'students',
      columns: [
        { name: 'tenant_id', type: 'string', isIndexed: true },
        { name: 'admission_no', type: 'string', isIndexed: true },
        { name: 'roll_no', type: 'string', isOptional: true },
        { name: 'first_name', type: 'string' },
        { name: 'last_name', type: 'string', isOptional: true },
        { name: 'middle_name', type: 'string', isOptional: true },
        { name: 'gender', type: 'string' },
        { name: 'dob', type: 'number' },
        { name: 'mobile_number', type: 'string', isOptional: true },
        { name: 'email', type: 'string', isOptional: true },
        { name: 'class_id', type: 'string', isOptional: true },
        { name: 'section_id', type: 'string', isOptional: true },
        { name: 'parent_id', type: 'string', isOptional: true },
        { name: 'is_active', type: 'boolean' },
        { name: 'student_photo', type: 'string', isOptional: true },
        { name: 'selected_fee_groups', type: 'string', isOptional: true },
        { name: 'fee_exclusions', type: 'string', isOptional: true },
        // Additional backend fields for complete sync
        { name: 'religion', type: 'string', isOptional: true },
        { name: 'caste', type: 'string', isOptional: true },
        { name: 'father_email', type: 'string', isOptional: true },
        { name: 'mother_email', type: 'string', isOptional: true },
        { name: 'admission_date', type: 'number', isOptional: true },
        { name: 'blood_group', type: 'string', isOptional: true },
        { name: 'genotype', type: 'string', isOptional: true },
        { name: 'state_of_origin', type: 'string', isOptional: true },
        { name: 'nationality', type: 'string', isOptional: true },
        { name: 'height', type: 'string', isOptional: true },
        { name: 'weight', type: 'string', isOptional: true },
        { name: 'as_on_date', type: 'number', isOptional: true },
        { name: 'category_id', type: 'string', isOptional: true },
        { name: 'house_id', type: 'string', isOptional: true },
        { name: 'user_id', type: 'string', isOptional: true },
        { name: 'father_name', type: 'string', isOptional: true },
        { name: 'father_phone', type: 'string', isOptional: true },
        { name: 'father_occupation', type: 'string', isOptional: true },
        { name: 'mother_name', type: 'string', isOptional: true },
        { name: 'mother_phone', type: 'string', isOptional: true },
        { name: 'mother_occupation', type: 'string', isOptional: true },
        { name: 'guardian_name', type: 'string', isOptional: true },
        { name: 'guardian_relation', type: 'string', isOptional: true },
        { name: 'guardian_phone', type: 'string', isOptional: true },
        { name: 'guardian_email', type: 'string', isOptional: true },
        { name: 'guardian_photo', type: 'string', isOptional: true },
        { name: 'guardian_address', type: 'string', isOptional: true },
        { name: 'emergency_contact', type: 'string', isOptional: true },
        { name: 'current_address', type: 'string', isOptional: true },
        { name: 'permanent_address', type: 'string', isOptional: true },
        { name: 'transport_route', type: 'string', isOptional: true },
        { name: 'vehicle_number', type: 'string', isOptional: true },
        { name: 'pickup_point', type: 'string', isOptional: true },
        { name: 'hostel_name', type: 'string', isOptional: true },
        { name: 'room_number', type: 'string', isOptional: true },
        { name: 'medical_conditions', type: 'string', isOptional: true },
        { name: 'previous_school_name', type: 'string', isOptional: true },
        { name: 'last_class_passed', type: 'string', isOptional: true },
        { name: 'special_physical_health_problems', type: 'string', isOptional: true },
        { name: 'has_disability', type: 'boolean', isOptional: true },
        { name: 'has_allergies', type: 'boolean', isOptional: true },
        { name: 'allergy_details', type: 'string', isOptional: true },
        { name: 'family_doctor_name', type: 'string', isOptional: true },
        { name: 'family_doctor_clinic_address', type: 'string', isOptional: true },
        { name: 'family_doctor_phone', type: 'string', isOptional: true },
        { name: 'first_aid_consent', type: 'boolean', isOptional: true },
        { name: 'catholic_faith_consent', type: 'boolean', isOptional: true },
        { name: 'is_baptized', type: 'boolean', isOptional: true },
        { name: 'is_communicant', type: 'boolean', isOptional: true },
        { name: 'application_fee_reference', type: 'string', isOptional: true },
        { name: 'undertaking_accepted', type: 'boolean', isOptional: true },
        { name: 'parent_signature', type: 'boolean', isOptional: true },
        { name: 'deactivated_at', type: 'number', isOptional: true },
        { name: 'deactivate_reason_id', type: 'string', isOptional: true },
        { name: 'discount_profile_id', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'attendance',
      columns: [
        { name: 'tenant_id', type: 'string', isIndexed: true },
        { name: 'student_id', type: 'string', isIndexed: true },
        { name: 'class_id', type: 'string', isIndexed: true },
        { name: 'section_id', type: 'string', isOptional: true },
        { name: 'date', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'remarks', type: 'string', isOptional: true },
        { name: 'session_id', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'fee_records',
      columns: [
        { name: 'tenant_id', type: 'string', isIndexed: true },
        { name: 'student_id', type: 'string', isOptional: true },
        { name: 'amount', type: 'number' },
        { name: 'type', type: 'string' },
        { name: 'payment_method', type: 'string' },
        { name: 'reference', type: 'string', isOptional: true },
        { name: 'fee_group_id', type: 'string', isOptional: true },
        { name: 'session_id', type: 'string', isOptional: true },
        { name: 'processed_by', type: 'string', isOptional: true },
        { name: 'school_section_id', type: 'string', isOptional: true },
        { name: 'meta', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'classes',
      columns: [
        { name: 'tenant_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'is_active', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'sections',
      columns: [
        { name: 'tenant_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'class_id', type: 'string', isIndexed: true },
        { name: 'is_active', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'fee_groups',
      columns: [
        { name: 'tenant_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'is_active', type: 'boolean' },
        { name: 'heads_json', type: 'string', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'fee_heads',
      columns: [
        { name: 'tenant_id', type: 'string', isIndexed: true },
        { name: 'fee_group_id', type: 'string', isIndexed: true },
        { name: 'name', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'default_amount', type: 'string' },
        { name: 'is_optional', type: 'boolean' },
        { name: 'is_active', type: 'boolean' },
      ],
    }),
    // ─── NEW TABLES (3-month rolling sync) ─────────────────────────
    tableSchema({
      name: 'exam_groups',
      columns: [
        { name: 'tenant_id', type: 'string', isIndexed: true, isOptional: true },
        { name: 'name', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'start_date', type: 'string' },
        { name: 'end_date', type: 'string' },
        { name: 'academic_year', type: 'string', isOptional: true },
        { name: 'term', type: 'string', isOptional: true },
        { name: 'is_active', type: 'boolean' },
        { name: 'is_published', type: 'boolean' },
        { name: 'session_id', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'student_term_results',
      columns: [
        { name: 'tenant_id', type: 'string', isIndexed: true, isOptional: true },
        { name: 'student_id', type: 'string', isIndexed: true, isOptional: true },
        { name: 'exam_group_id', type: 'string', isOptional: true },
        { name: 'class_id', type: 'string', isOptional: true },
        { name: 'section_id', type: 'string', isOptional: true },
        { name: 'session_id', type: 'string', isOptional: true },
        { name: 'total_score', type: 'number' },
        { name: 'average_score', type: 'number' },
        { name: 'position', type: 'number', isOptional: true },
        { name: 'total_students', type: 'number', isOptional: true },
        { name: 'principal_comment', type: 'string', isOptional: true },
        { name: 'teacher_comment', type: 'string', isOptional: true },
        { name: 'days_present', type: 'number' },
        { name: 'days_opened', type: 'number' },
        { name: 'status', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'student_documents',
      columns: [
        { name: 'tenant_id', type: 'string', isIndexed: true, isOptional: true },
        { name: 'student_id', type: 'string', isIndexed: true },
        { name: 'title', type: 'string' },
        { name: 'file_path', type: 'string' },
        { name: 'file_type', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'communication_logs',
      columns: [
        { name: 'tenant_id', type: 'string', isIndexed: true },
        { name: 'type', type: 'string' },
        { name: 'recipient', type: 'string' },
        { name: 'recipient_name', type: 'string', isOptional: true },
        { name: 'subject', type: 'string', isOptional: true },
        { name: 'body', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'error_message', type: 'string', isOptional: true },
        { name: 'provider_message_id', type: 'string', isOptional: true },
        { name: 'student_id', type: 'string', isIndexed: true, isOptional: true },
        { name: 'staff_id', type: 'string', isOptional: true },
        { name: 'parent_id', type: 'string', isOptional: true },
        { name: 'scheduled_at', type: 'number', isOptional: true },
        { name: 'delivered_at', type: 'number', isOptional: true },
        { name: 'opened_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'fee_groups',
      columns: [
        { name: 'tenant_id', type: 'string', isIndexed: true, isOptional: true },
        { name: 'name', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'is_active', type: 'boolean' },
        // Embedded fee heads stored as a JSON string: [{id, name, defaultAmount, isOptional, isActive}]
        { name: 'heads_json', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
  ],
});
