import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { api } from '../../services/api';
import { useSystem } from '../../context/SystemContext';
import { ReceiptTemplate } from './components/ReceiptTemplate';
import { ShieldCheck, AlertTriangle } from 'lucide-react';
import { printReceipt } from './utils/printReceipt';

export const VerifyReceiptPage: React.FC = () => {
    const { id } = useParams<{ id: string }>();
    const [transaction, setTransaction] = useState<any>(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);
    const { getSchoolInfo, getFullUrl, formatCurrency } = useSystem();
    const schoolInfo = getSchoolInfo();

    useEffect(() => {
        const fetchReceipt = async () => {
            if (!id) {
                setError('No receipt ID provided.');
                setLoading(false);
                return;
            }

            try {
                // Public endpoint call
                const response = await api.verifyPublicReceipt(id);
                setTransaction(response);
            } catch (err: any) {
                console.error(err);
                setError(err.response?.data?.message || 'Verification Failed: Receipt not found or invalid.');
            } finally {
                setLoading(false);
            }
        };

        fetchReceipt();
    }, [id]);

    if (loading) {
        return (
            <div className="min-h-screen bg-gray-50 flex flex-col items-center justify-center">
                <div className="w-16 h-16 border-4 border-primary-500 border-t-transparent rounded-full animate-spin"></div>
                <p className="mt-4 text-gray-500 font-medium">Verifying Secure Receipt...</p>
            </div>
        );
    }

    if (error || !transaction) {
        return (
            <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
                <div className="bg-white max-w-md w-full rounded-2xl shadow-xl overflow-hidden text-center p-8">
                    <div className="mx-auto w-20 h-20 bg-red-100 rounded-full flex items-center justify-center mb-6">
                        <AlertTriangle className="w-10 h-10 text-red-600" />
                    </div>
                    <h1 className="text-2xl font-black text-gray-900 mb-2">Invalid Receipt</h1>
                    <p className="text-gray-500 mb-8">{error}</p>
                    <Link to="/" className="inline-block bg-primary-600 text-white px-6 py-3 rounded-xl font-bold hover:bg-primary-700 transition-colors">
                        Return to Homepage
                    </Link>
                </div>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-gray-50 flex flex-col">
            {/* Minimal Header */}
            <header className="bg-indigo-900 text-white shadow-md">
                <div className="max-w-7xl mx-auto px-4 h-16 flex items-center justify-between">
                    <div className="flex items-center gap-3">
                        <img src={schoolInfo.logo} alt="Logo" className="h-8 w-auto bg-white rounded-md p-1" />
                        <span className="font-bold hidden sm:block">{schoolInfo.name}</span>
                    </div>
                    <div className="flex items-center gap-2 text-green-400 bg-white/10 px-4 py-1.5 rounded-full backdrop-blur-sm shadow-inner">
                        <ShieldCheck className="w-5 h-5" />
                        <span className="text-sm font-bold tracking-wide">VERIFIED SECURE RECORD</span>
                    </div>
                </div>
            </header>

            {/* Receipt Content */}
            <main className="flex-grow py-8 px-4 sm:px-6 lg:px-8">
                <div className="max-w-4xl mx-auto mb-8">
                    <div className="bg-white rounded-2xl shadow-lg border border-gray-200 overflow-hidden print:shadow-none print:border-none">
                        <div className="bg-green-50 border-b border-green-100 p-6 flex flex-col sm:flex-row items-center justify-between print:hidden">
                            <div>
                                <h2 className="text-lg font-black text-green-900 mb-1">Authentic Transaction Verified</h2>
                                <p className="text-sm text-green-700">This receipt is a valid official record generated by our systems.</p>
                            </div>
                            <button 
                                onClick={() => printReceipt({ transaction, schoolInfo })}
                                className="mt-4 sm:mt-0 bg-white text-green-800 border-2 border-green-200 hover:border-green-300 hover:bg-green-50 px-6 py-2.5 rounded-xl font-bold tracking-wide transition-all shadow-sm"
                            >
                                Print Official Copy
                            </button>
                        </div>
                        <div className="overflow-x-auto">
                            <ReceiptTemplate transaction={transaction} schoolInfo={schoolInfo} />
                        </div>
                    </div>
                </div>
            </main>
        </div>
    );
};
